Added first page
Moathal/portfolio pull request #1
Opened 2022-06-29 19:43 UTC by Moathal

- Added README and MIT with their details.
- Created index.html file with toolbar header and headline section.
    1.    header (toolbar):
           - span (logo).
           - button.
    2.   section (headline):
          - h1 (mainTxt).
          - h3 (spprtTxt).
         
- Added CSS file flex layout and styling for each element with color and background, font, and sizing.

2022-06-29 20:40 UTC, Lucas-Masaba requested changes
# Hello @Moathal  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Clean code 🧹 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-29 20:40 UTC, Lucas-Masaba commented on index.html
> +            <span class="theme logo"> Mo&lsquo;athal S. Kachi</span>
- [ ] Please wrap this with an `a` tag since it is a logo 👍

2022-06-29 20:40 UTC, Lucas-Masaba commented on index.html
> +            <button></button>
- [ ] Please wrap this hamburger button in a `nav` tag. The hamburger button contains navigation links to different places on your portfolio as you will see in the future 👌

2022-06-29 20:40 UTC, Lucas-Masaba commented on index.html
> +</html>
- [ ] You are missing a great deal of content. 
### Currently, your page looks like this
![image](https://user-images.githubusercontent.com/45460192/176540151-878bc781-9e3e-4b69-be87-4644ccd5495d.png)
### It should look like this
![image](https://user-images.githubusercontent.com/45460192/176540399-1e04fc0e-c252-4da7-8a07-202a06f361b3.png)

2022-06-30 15:21 UTC, danmainah requested changes
Hi @Moathal , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 15:21 UTC, danmainah commented on index.html
> +
- [ ] @Moathal great work implementing the changes requested, however, there is a small mistake on your languages and frameworks, ensure the content is aligned as in the given design:
<img width="178" alt="image" src="https://user-images.githubusercontent.com/61408860/176714925-2f8928b0-f713-403b-8224-f732ab28240b.png">

2022-06-30 16:41 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Moathal        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 16:48 UTC, merged